"""
validate_plan — ADK FunctionTool that runs Layer B (command compiler) on a
plan generated by plan_agent in interactive / CLI mode.

In the batch pipeline (app/main.py → PlanAgent.generate()), all three
validation layers run inside the Python class before the plan is returned.
In the ADK interactive path the plan_agent sub-agent writes raw JSON to
session state and bypasses PlanAgent.generate() entirely — this tool bridges
that gap by running the command compiler before the root agent presents the
plan or dispatches for approval.

Layer A (maintenance window) and Layer C (gcloud subprocess dry-run) are
intentionally omitted here:
  - Layer A requires CustomerConfig, which is not available in interactive sessions.
  - Layer C (subprocess) is inappropriate inside a synchronous ADK tool call.
Both layers still run in the full batch pipeline via PlanAgent.generate().
"""
from app.tools.command_compiler import compile_plan


def validate_plan(plan: dict, finding: dict) -> dict:
    """
    Validates a remediation plan against the command compiler (Layer B).

    Checks every api_call string in plan.steps and plan.rollback_steps for:
      - Hard-blocked subcommands (deletions, terraform destroy)
      - IAM expansion (add-iam-policy-binding)
      - Firewall expansion (source-ranges to 0.0.0.0/0 or ::/0)
      - Subcommand whitelist for the plan's remediation_type
      - Project scope (--project must match finding's project)

    Args:
        plan: The plan dict from plan_agent_output session key.
        finding: The current finding dict (needs resource_name for scope check).

    Returns:
        {
          "passed": bool,
          "blocked": bool,
          "violations": list[str],   # empty when passed=True
          "block_reason": str | None # set when blocked=True
        }
    """
    result = compile_plan(plan, finding)

    block_reason = None
    if not result.passed:
        block_reason = "Command compiler violations: " + "; ".join(result.violations)

    return {
        "passed": result.passed,
        "blocked": not result.passed,
        "violations": result.violations,
        "block_reason": block_reason,
    }
